### ISSUE TITLE
Please add the mnemonic seed word for generating and recover wallet.

### ISSUE THREAD

**Issue by artiya4u** [icon-project/iconex_chrome_extension#1]
Please add the mnemonic seed word for generating and recover wallet as describe on
https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki

**Comment by qaher86** [comment]
**When are we going to see Mnemonic support in ICONex wallet?!**

**Comment by yjini03** [comment]
There are no plans to support the mnemonic seed word.
If you want to use mnemonic support, please use Ledger Nona S.
