### ISSUE TITLE
Update password validation code

### ISSUE THREAD

**Issue by Spl3en** [icon-project/iconex_chrome_extension#11]
https://github.com/icon-project/iconex_chrome_extension/blob/20dad183ae718db7684ada1bf2c1525ba6822893/src/app/components/Common/ValidationForm.js#L116
https://github.com/icon-project/iconex_chrome_extension/blob/20dad183ae718db7684ada1bf2c1525ba6822893/src/app/components/Common/ValidationForm.js#L119

Both conditions could be simplified into one : 
```javascript
  else if(!(/^(?=.*\d)(?=.*[a-zA-Z])(?=.*[!@#$%^&*()_+{}:<>?]).{8,}$/.test(this.state.pw))) {
    pwError = I18n.error.pwErrorMix
    break;
  }
```

Also, for consistency purposes across ICONex versions, the special characters should remain the same in order to avoid unexpected incompatibilities.

ICONex iOS password regexp : https://github.com/icon-project/iconex_ios/blob/03e102736d89a0d1d78b7bd08eba5b390452842f/iconex_ios/Sources/ICONex/Utils/IXUtils.swift#L404
ICONex Android password regexp : https://github.com/icon-project/iconex_android/blob/1fbe194465e0eef55344b00cd4f726dee40b8cdf/app/src/main/java/foundation/icon/iconex/MyConstants.java#L65

**Comment by couldseeme** [comment]
We merged your PR. Thank you.
