### ISSUE TITLE
Oddly formatted private key is still imported in ICONex

### ISSUE THREAD

**Issue by Spl3en** [icon-project/iconex_chrome_extension#14]
Following a report from a Telegram user, I spotted a weird bug in ICONex that lets a user import a oddly formated private key in ICONex. 

Here's an exemple of a boggus private key that is correctly imported in ICONex : 
```a_a_a_a_a_a_a_a_a_a_a_a_a_a_a_a_a_a_a_a_a_a_a_a_a_a_a_a_a_a_a_a_```

![wtf](https://i.imgur.com/3ZPnCDI.gif)

As you may see, the private key is accepted as long as it is 64 characters and, for each byte, if the most significant nibble is an hexadecimal character, **but** the least significant may **be anything**.

On Chrome, such private key is parsed as ```Uint8Array(32) [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]```. (`0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a`) - in other words, the parsing for each byte stops whenever it encounters an invalid hexadecimal characters, but keeps parsing the rest of the string if the bad character is the least significant nibble.

Here's the suspected line of source code : 

https://github.com/icon-project/iconex_chrome_extension/blob/49ffade64e406a22a869132e44009dbfa402d50d/src/app/components/Popup/_02_importWallet/ImportWallet_3.js#L51

I believe it is a bug in the `new Buffer(string[, encoding])` call. This function shouldn't return a valid array if there are invalid hexadecimal characters in the string - but it does.

![](https://i.imgur.com/D1UKAZI.png)

Video showing how to reproduce the bug : https://gfycat.com/fr/SpotlessDenseGermanspitz

Edit : It looks like this issue is also being discussed last week on the Node repository : https://github.com/nodejs/node/issues/24722

**Comment by couldseeme** [comment]
Thank you for reporting issue.
Since we've [fixed](https://github.com/icon-project/iconex_chrome_extension/commit/67bf1731f1d95191fe16f8db2987529e07d5ce15) this problem, we close the issue.
