### ISSUE TITLE
Password - Special Characters Issue

### ISSUE THREAD

**Issue by radiofriendly** [icon-project/iconex_chrome_extension#15]
Hello team - Providing some user feedback regarding the ICONex wallet and password functionality.

There are 2 special characters that cannot be entered when creating a password (that we have found).  The characters are:

`=;`
I guess some users have tried to enter a semicolon or equals sign when creating their passwords during the wallet creation process.  They did not use the "show password" functionality at the screen below and thought that the special characters above were included.  ICONex does not enable you to use these characters during password creation.

However, if you go to unlock your wallet, ICONex will allow you to enter these characters which results in a failed password notification.

Is there any way to prevent these particular special characters from being used in the unlock password prompt?  If so - I think that might be helpful to these users that are experiencing this issue.  Either that, or a notice on the screen below that shows what special characters are permitted, perhaps?

Not sure about the solution - I'll leave that up to the team, of course.  Just wanted to relay an issue that has affected a few users.

**Comment by Spl3en** [comment]
Ideally, these characters should be included in the characters set. They were omitted in the PR#12, my bad.

**Comment by jorisvial** [comment]
Closing because it's too old. Feel free to re-open if you feel like a change is required.
