### ISSUE TITLE
ICON wallet not reliably appearing quickly

### ISSUE THREAD

**Issue by Meai1** [icon-project/iconex_chrome_extension#19]
First of all, it is weird that when I cancel and then click again, it almost always opens up quickly.
But many times it never opens up, I wait for like 30+ seconds.
In my opinion: 
It should not need a server roundtrip at all to display something and be functional. Hide the ICX balances or whatever you're getting from the network and just show me the addresses. Most of the time I already know what the balance is, I dont want to wait to use the wallet just to get the absolut latest network update. 

Surely I can send ICX transactions even without getting any server network information. Yes, when I actually send it will need to contact some server. But everything until that point should not need a server or at least gracefully hide information that it cant get at the moment. Like lets say you can add an indicator saying: "Getting updates from ICON.." if it isnt ready yet. But I still want to be able to click on wallets and inspect stuff and send transactions, even if it isnt ready yet.

**Comment by pieman64** [comment]
Several devs on the ICON tx challenge have noticed issues with the extension. Could ICON review the usage and make the appropriate changes, thanks.

**Comment by BLOC8app** [comment]
We have also noticed that the wallet fails to become available on some requests.

**Comment by ajaya-man** [comment]
I have also experienced such issues. First popup doesn't comes quickly, cancelling and doing it again brings it quickly.

**Comment by jorisvial** [comment]
Closing because it's too old. Feel free to re-open if you feel like a change is required.
