### ISSUE TITLE
How do I access the wallet from a webpage? Please describe the api.

### ISSUE THREAD

**Issue by Meai1** [icon-project/iconex_chrome_extension#2]
With Metamask people can use the wallet to easily pay for something on the website. 
Required features I can think of: 
1. some way to get the user's address
2. some way to prompt the wallet to fill out the destination address for a payment request
3. let me show some icon too please
4. let me add custom transaction data
5. then after the transaction is done, I need to get the tx info back of course so I can verify it on my side

**Comment by yjini03** [comment]
We are preparing to access the iconex from a webpage.
We will relaese it as soon as we are ready.
