### ISSUE TITLE
Proposal: "Fastwallet" concept for dapps

### ISSUE THREAD

**Issue by Meai1** [icon-project/iconex_chrome_extension#20]
**Problem:**
A game may need to send quite a few transactions constantly, they are cheap but asking for the wallet popup and password everytime disrupts the gaming usecase. 
Even a single "ok" is probably going to be too annoying. 

**Proposed solution:**
So a general concept like Android permissions would be nice, where in the case of the iconex wallet it would create a fastwallet for each dapp and then the dapp can ask for some amount to operate properly. Lets say 3 ICX so the game can store state and progress and do stuff for you and the user may allow passwordless access from the dapp to the fastwallet for these max. of 3 ICX just by entering his password once per dapp per gaming (or otherwise) session.

Application<-> Fast Wallet <-> Real Wallet

**Comment by BLOC8app** [comment]
In the real world where real people are killed by lunatics and serial killers they also require these same features in the smartphone version of the wallet. We pointed this out on the forum some weeks ago.

Hope this can be supported by the big team of ICON developers.

**Comment by Spl3en** [comment]
I confirm such feature would be useful for the game DApp I'm building.

I expect the player to interact with his wallet every 5-10 seconds, and I cannot expect the player to input his wallet password repeatedly without harming the fun of playing the game.

My current solution employs a "fast wallet" keystore, stored in the browser localStorage, and the keystore password is stored in the sessionStorage and needs the user to input it regularly. Very similar concept to what @Meai1 is suggesting.

One of the issue I'm facing with that solution, is if the user forgets about withdrawing funds from his fast wallet at the end of the session.

**Comment by jorisvial** [comment]
Closing because it's too old. Feel free to re-open if you feel like a change is required.
