### ISSUE TITLE
Unable to vote from Ledger Wallet easily

### ISSUE THREAD

**Issue by dacoinvid** [icon-project/iconex_chrome_extension#23]
Hi,

Currently, it's unable to "Connect to Ledger", then vote.
There is a prerequisite step of "Create Wallet".

See https://medium.com/posbakerz/how-to-stake-vote-in-icon-icx-5926e8e8a54b

Thanks

**Comment by jorisvial** [comment]
Closing because it's too old. Feel free to re-open if you feel like a change is required.
