### ISSUE TITLE
Bypass Passcode Screenlock (With Physical Access To ICONex)

### ISSUE THREAD

**Issue by jpopxfile** [icon-project/iconex_chrome_extension#26]
Hi,

I have raised an issue on Hackerone (ICON Bug Bounty Program) regarding the issue stated in the title. You can see the details regarding it, including a video on how a bypass can be done, in the Hackerone bug report link below.

https://hackerone.com/bugs?report_id=694300

The Hackerone staff has closed it as informative stating that is a theoretical issue, but no ICON team member has been a participant of that report, so I don't think this report has been seen by any ICON team member.

The bounty brief does not state vulnerabilities that require physical access as being out of scope, so in my opinion, it is a valid issue which bypasses a security measure of ICONex. If the ICON team is interested in bugs that allow the bypass the 6 digit passcode screenlock, please check the report and follow up on it.

Either way, I hope to hear back about this. Thanks.

**Comment by jorisvial** [comment]
Closing because it's too old. Feel free to re-open if you feel like a change is required.
