### ISSUE TITLE
Unable to swap eth token to mainnet token from within last chrome extension

### ISSUE THREAD

**Issue by chisNaN** [icon-project/iconex_chrome_extension#3]
Hello.

I tried TWICE to swap eth icx token (approx 125) using

- 67.0.3396.99 version of chrome
- 1.0.1.32 version of iconex wallet chrome extension

and each time transaction failed with the following errors:
```
 Warning! Error encountered during contract execution [Reverted] 
  ERC-20 Token Transfer Error (unable to locate corresponding Transfer event log), check with sender
```
with these network fees datas:

```
Gas Limit: 55000
Gas Used By Txn: 23580
Gas Price: 0.000000021
Ether (21 Gwei)
Actual Tx Cost/Fee: 0.00049518 Ether ($0.21)
```

here is my iconex eth public wallet address so you can check:

https://etherscan.io/address/0x6fe4b4367beaa556a38e97f730a05677ceb70fbe

After these 2 failled attempts i dont have the required eth to make the transaction as says this official spreadsheet:

https://docs.google.com/spreadsheets/d/1HiT98wqEpFgF2d98eJefQfH7xK4KPPxNDiiXg3AcJ7w/edit#gid=0

"The default setting is 21 Gwei, 69682 gas limit. Approximately 0.002 ETH would be enough."

Any WORKING SOLUTION before spending eth again would be appreciated before the swap period is over of course.

Thanks

**Comment by chisNaN** [comment]
I think I solved my issue by:

- removing browser cache
- reinstalling extension

and especially NOT SWAPPING THE WHOLE BALANCE

**Comment by yjini03** [comment]
A bug where whole balances are not swapped has been fixed.
Please install and check latest iconex version.(1.0.2.22)
