### ISSUE TITLE
Show all tokens held in the wallet by default

### ISSUE THREAD

**Issue by Spl3en** [icon-project/iconex_chrome_extension#31]
Following a comment from Mark Thomas from ZenSports :

Recommended feature for the ICONex wallet -- show all tokens held in the wallet BY DEFAULT instead of requiring someone to add the contract address to the wallet to view them (if they want to not view tokens for a wallet, just give the ability to remove viewing them).

We get like 3-5 customer support inquiries per week from SPORT and SPORTS token holders, asking why they can't see their tokens in their ICONex wallet. We then have to provide them the instructions to add the token contract to their wallet in order to view them. It's a pain and frustrating for customers.

**Comment by jorisvial** [comment]
Closing because it's too old. Feel free to re-open if you feel like a change is required.
