### ISSUE TITLE
Cannot sign a simple ICX transfer (icx_sendTransaction) with ICONex

### ISSUE THREAD

**Issue by Spl3en** [icon-project/iconex_chrome_extension#34]
https://github.com/icon-project/iconex_chrome_extension/blob/9816b55e93b000a0d73723628035b9e1c0a8c97f/src/app-popup/components/SendTransaction.js#L216

The "SendTransaction" method is looking for a `data` field in the transaction, which **doesn't exist** in a simple ICX transfer according to the [JSON-RPC documentation ](url): 

![https://i.imgur.com/dHOUKMR.png](https://i.imgur.com/dHOUKMR.png)

Consequently, as `data` is undefined, the code above will throw an error and ICONex will fail to sign any transaction that is a simple ICX transfer.

![https://i.imgur.com/evz1SAq.png](https://i.imgur.com/evz1SAq.png)

ICONex when this error occurs : 

![https://i.imgur.com/WOQeitS.png](https://i.imgur.com/WOQeitS.png)

**Comment by Spl3en** [comment]
For anyone else having this bug in the meantime, there is a workaround : 

Right before send your payload to `REQUEST_JSON-RPC`, forge a params.data field in your JSON RPC query, by doing so : 

```js
jsonRpcQuery.params.data = ""
```

Example of the workaround here : https://github.com/iconation/Ancilia/blob/52f5905257bc5353b60028bff3dae8869a766cf2/Ancilia.js#L191

**Comment by jorisvial** [comment]
Closing because it's too old. Feel free to re-open if you feel like a change is required. Also, there are currently no issues sending ICX.
