### ISSUE TITLE
Popup not showing properly

### ISSUE THREAD

**Issue by sharma66mahesh** [icon-project/iconex_chrome_extension#35]
The buttons on the popup screen are not showing up while Using chrome with 100% zoom on a 720p screen. If the contents don't fit the browser window size, there should be an option to scroll down.

![Screenshot from 2020-07-07 12-22-24](https://user-images.githubusercontent.com/24717327/86804248-7c399f80-c096-11ea-96df-a46c353a7d56.png)

Zooming out the browser window brings it back though.
![Screenshot from 2020-07-07 12-22-40](https://user-images.githubusercontent.com/24717327/86804256-7e036300-c096-11ea-9188-3ffe495a4180.png)

**Comment by jorisvial** [comment]
Closing because it's too old. Feel free to re-open if you feel like a change is required.
