### ISSUE TITLE
Wallet doesn't unlock with it's password

### ISSUE THREAD

**Issue by realphi** [icon-project/iconex_chrome_extension#36]
Hello,
I created a wallet in ICONex and set a password for it. When I tried to unlock the wallet, it always says "Check your password". But I was sure my password was correct. I created another wallet with the same password and it can't unlock either. So it seems there is a bug in the extension with some kind of password strings.

The password is:
```
YCKSw[tVmyR5{)BfCKx35c7pPq,%0;hK8KD]d52uc9M=18XHbvq06bTzDlk?g0a
```

Strangely you can't paste anything in the password field when creating a wallet, so I used an auto typer tool named "Autosofted Auto Typer" to automatically type the password. But I don't think it causes an issue because it types exactly what you paste in it.

It's important for me to unlock my wallet, I've some funds in it and I can't access them right now.
Thanks in advance

**Comment by Spl3en** [comment]
Hi @realphi,

The ICONex Wallet doesn't accept `=` as a valid character.

Only these characters are accepted : `?!:\.,%+-/*<>{}()[]`"'~_^\|@#$&`.

Try to input your password without the `=` and it should unlock.

**Comment by realphi** [comment]
> 
> 
> Hi @realphi,
> 
> The ICONex Wallet doesn't accept `=` as a valid character.
> 
> Only these characters are accepted : `` ?!:\.,%+-/*<>{}()[]`"'~_^\|@#$& ``.
> 
> Try to input your password without the `=` and it should unlock.

It didn't work :(

**Comment by Spl3en** [comment]
I also noticed there's a `;` character in your password that isn't in the password list. Also remove that.

**Comment by realphi** [comment]
> I also noticed there's a `;` character in your password that isn't in the allowed character list. Try removing it.
> Your password should be :
> 
> `YCKSw[tVmyR5{)BfCKx35c7pPq,%0hK8KD]d52uc9M18XHbvq06bTzDlk?g0a`

Thanks it worked! 👍

**Comment by Spl3en** [comment]
You're welcome! Please close this issue if you have no further request 👍

**Comment by rikky505** [comment]
Hello, I created an Iconex wallet in 2019 and went to withdraw it this year and it says my password is incorrect when I have specifically written down my password and also have my private key stored. Neither my password or private key worked. My private key that I saved in since making my iconex wallet just loads a blank wallet with no balance. Help please :/

**Comment by ICONationTeam** [comment]
@rikky505 Please make sure your password doesn't contain any invalid character as stated above.

If you import your funds with your private key, please triple check if you wrote it correctly.
If the imported private key is empty with 0 transaction in the transaction history, then it means you didn't write correctly your private key.

Would you have your public address somewhere? So you can check when your private key matches with your public address.

**Comment by jorisvial** [comment]
Closing as we did not hear from @rikky505 for a couple of months now, suggesting that he accessed his funds already.
