### ISSUE TITLE
Can't deploy contract when change wallet password 

### ISSUE THREAD

**Issue by vinhyenvodoi98** [icon-project/iconex_chrome_extension#37]
For some reason I have to change the wallet password. However, after the change, i cannot be deploy contract, even though the new keystore has been downloaded and have an error **Password is wrong** .And now I cannot deploy even with old password or the new one.

I tested importing the wallet from the keystore back into the wallet and it still works.

**Comment by Spl3en** [comment]
Hello, please can you confirm you're not having this issue : https://github.com/icon-project/iconex_chrome_extension/issues/36#issuecomment-667048397 ?

**Comment by vinhyenvodoi98** [comment]
@Spl3en yep i'm pretty sure it doesn't look like #36 . After I change my password I still use it as usual. including importing it into another wallet. The only problem is inability to deploy the contract because it shows an error "password is wrong"

**Comment by Spl3en** [comment]
The "password is wrong" is coming from the Chrome ICONex extension, right ?

**Comment by vinhyenvodoi98** [comment]
@Spl3en no it from Tbears when i deploy contract

**Comment by Spl3en** [comment]
Could you please trying to deploy using the Audit tool ? audit.icon.foundation
