### ISSUE TITLE
How can I detect if the ICONex extension is installed?

### ISSUE THREAD

**Issue by WeiLi512** [icon-project/iconex_chrome_extension#38]
How can I detect if the ICONex extension is installed?
I need this feature to redirect users to the ICONex extension installation.

I'd like ICONex to support this feature like Metamask
https://docs.metamask.io/guide/getting-started.html#basic-considerations

**Comment by jorisvial** [comment]
Closing because it's too old. Feel free to re-open if you feel like a change is required.
