### ISSUE TITLE
Wrong MyEtherWallet API address in live 1.0.2.13 ICONex

### ISSUE THREAD

**Issue by Spl3en** [icon-project/iconex_chrome_extension#6]
https://github.com/icon-project/iconex_chrome_extension/blob/3b13d0ce8f6c366239382523a46256cbce3a463f/src/constants/config.js#L52

This API address is correct in the released source code version 1.0.2.13 on Github, **however** in the live ICONex version 1.0.2.13, it still contains the wrong API address : 

```
export var ETH_SERVER = function ETH_SERVER() {
  var ethServer = getCurrentServer('eth');
  var obj = {
    'ropsten': 'https://ropsten.infura.io/',
    'main': 'https://api.myetherapi.com/eth'  // <--- Wrong !
  };
  return obj[ethServer];
};
```

![ICONex Screenshot](https://i.imgur.com/wvuZA2D.png)

**Comment by spood** [comment]
Looks like this change was already made in the source code.

**Comment by Spl3en** [comment]
Fixed, thanks.
