### ISSUE TITLE
Can't open extension after the recent update of 2.0.1 in Brave

### ISSUE THREAD

**Issue by ajaya-man** [icon-project/iconex_chrome_extension#67]
After the recent update, can't open the existing ICONex extension. It shows following issue:

`Uncaught TypeError: Cannot read properties of undefined (reading 'community')
    at ICX_TRACKER_SERVER (store.bundle.js:117395:24)
    at Object../src/constants/config.js (store.bundle.js:117467:8)
    at __webpack_require__ (store.bundle.js:20:30)
    at Object../src/utils/utils.js (store.bundle.js:126875:78)
    at __webpack_require__ (store.bundle.js:20:30)
    at Object../src/utils/index.js (store.bundle.js:126659:65)
    at __webpack_require__ (store.bundle.js:20:30)
    at Object../src/redux/api/walletIcxApi.js (store.bundle.js:125734:64)
    at __webpack_require__ (store.bundle.js:20:30)
    at Object../src/background/background.js (store.bundle.js:116993:81)`

ICONex version 2.0.1
Brave Version 
[Version 1.36.122 Chromium: 99.0.4844.88 (Official Build) (x86_64)](https://brave.com/latest/)

**Comment by bykim-iconloop** [comment]
I am checking it now, but the error situation is not reproduced. Now, we suggest reinstalling the app as a way to solve the error situation. We will continue to check the error condition.

**Comment by ajaya-man** [comment]
I found a way to reproduce. Previously we used to set isDev true in local storage to change the testnet network. This used to create two fields in local storage. I removed those two local storage values and now it's working. The new configuration seems to be not compatible with the previous local storage value.

**Comment by ajaya-man** [comment]
Also, I was on Sejong network previously which has been removed currently. I think the main reason is this one.

**Comment by bykim-iconloop** [comment]
I got it. What you're talking about seems to be the cause of the problem. I'll have to check that part out.

**Comment by ajaya-man** [comment]
Open ICONex Chrome Extension: chrome-extension://flpiciilemghbmfalicajoolhkkenfel/index.html#/

Then F12, then Application then local storage, and delete the `icxServer = sejong` key value.

Add the following key values if you still want sejong.
```
customIcxServer : {"customWalletURL":"https://sejong.net.solidwallet.io","customTrackerURL":"https://sejong.tracker.solidwallet.io","customNid":"0x53"}
icxServer : custom
```

This will enable sejong in iconex.
