### ISSUE TITLE
Issue in setting custom ICX server

### ISSUE THREAD

**Issue by ajaya-man** [icon-project/iconex_chrome_extension#68]
The button to set custom icx server is not clickable in the new update. 
<img width="898" alt="image" src="https://user-images.githubusercontent.com/16894496/161008035-4380305a-f281-482e-aca4-2596ec97b385.png">
The button in korean is used to set the custom icx server but it's not clickable with the new update. 

Sejong has been removed with the new update and we are still testing large number of scores in sejong but this update creates problem in working with sejong testnet.

**Comment by bykim-iconloop** [comment]
I will check the issue. and Awaiting the outcome of the discussion about sejeong testnet.

**Comment by bykim-iconloop** [comment]
This is solved in v.2.0.2
