### ISSUE TITLE
The Swap button does not show up in MyWalletBar due to case-sensitive address comparison

### ISSUE THREAD

**Issue by alobakov** [icon-project/iconex_chrome_extension#7]
The line in MyWalletBar.js that reads 
`const isSwapAvailable = tokenId === ICX_TOKEN_CONTRACT_ADDRESS()`
does not account for the fact that the contract address pasted by the user while adding the ERC-20 ICX token may have uppercase characters just like the real ETH address of the contract does.
The case-specific address was provided to the community in the following [document](https://docs.google.com/document/d/18UCJNNwgeTGIwnsD7STcR2nKJcn0hfJ92h0XHwRIWE8/edit).
However, the ERC-20 ICX contract addresses defined in ICX_TOKEN_CONTRACT_ADDRESS() for both the testnet and mainnet are in lowercase, thereby causing the condition to fail and the Swap button to remain invisible.

**Comment by alobakov** [comment]
A similar bug is also found in CoinDetailContent.js as the same Swap button visibility logic is present there too.

**Comment by alobakov** [comment]
As a temporary workaround, users experiencing this issue should delete the custom token and re-add it using the contract address in lower case.

**Comment by couldseeme** [comment]
Thanks for reporting the issue. As we merged your PR, we close this issue.
